apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-exporter.fullname" . }}-config
data:
  config.yaml: |
    {{- if .Values.config.git }}
    git:
    {{ toYaml .Values.config.git | nindent 6 }}
    {{- else }}
    git: []
    {{- end }}

    {{- if .Values.config.rest_api }}
    rest_api:
    {{ toYaml .Values.config.rest_api | nindent 6 }}
    {{- else }}
    rest_api: []
    {{- end }}

    {{- if .Values.config.docker }}
    docker:
    {{ toYaml .Values.config.docker | nindent 6 }}
    {{- else }}
    docker: []
    {{- end }}
