name: Publish Helm Chart to GHCR

on:
  push:
    tags:
      - "v*"

jobs:
  helm-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package chart
        run: helm package ./prometheus-exporter-custom

      - name: Push chart to GHCR
        run: |
          CHART=$(ls prometheus-exporter-*.tgz)
          helm push $CHART oci://ghcr.io/${{ github.repository_owner }}/charts
