name: Build & Push to GHCR

on:
  push:
    branches: [main]
    # tags:
    #   - 'v*'
    paths:
      - '**.go'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - 'config.yaml'
      - '.github/workflows/publish.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    env:
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Convert image name to lowercase
        id: vars
        run: |
          IMAGE_REPO=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          echo "repo=${IMAGE_REPO}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags
        id: tags
        run: |
          echo "latest_tag=ghcr.io/${{ steps.vars.outputs.repo }}:latest" >> $GITHUB_OUTPUT
          echo "sha_tag=ghcr.io/${{ steps.vars.outputs.repo }}:${{ github.sha }}" >> $GITHUB_OUTPUT
          
          # if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
          #   version_tag="ghcr.io/${{ steps.vars.outputs.repo }}:${GITHUB_REF_NAME}"
          #   echo "version_tag=$version_tag" >> $GITHUB_OUTPUT
          # fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.tags.outputs.latest_tag }}
            ${{ steps.tags.outputs.sha_tag }}
            # ${{ steps.tags.outputs.version_tag }}
