name: Publish Helm Chart to GHCR

on:
  push:
    tags:
      - "v*"

jobs:
  helm-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Normalize repo owner to lowercase
        id: vars
        run: |
          echo "repo_owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Package chart
        run: helm package ./helm

      - name: Push to GHCR
        run: |
          CHART=$(ls prometheus-exporter-*.tgz)
          helm push "$CHART" oci://ghcr.io/${{ steps.vars.outputs.repo_owner }}/charts
