name: Release (Docker + Helm)

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Normalize repo names
        id: vars
        run: |
          docker_repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          chart_owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "docker_repo=$docker_repo" >> $GITHUB_OUTPUT
          echo "chart_owner=$chart_owner" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT  # v1.2.3

      - name: Log in to GHCR (Docker + Helm)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ######################
      # 🐳 Build Docker Image
      ######################
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.docker_repo }}:latest
            ghcr.io/${{ steps.vars.outputs.docker_repo }}:${{ steps.vars.outputs.version }}
            ghcr.io/${{ steps.vars.outputs.docker_repo }}:${{ github.sha }}

      ######################
      # ⎈ Package Helm Chart
      ######################
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Package Helm Chart
        run: |
          sed -i "s/^version: .*/version: ${GITHUB_REF_NAME#v}/" helm/Chart.yaml
          helm package ./helm

      - name: Push Helm Chart to GHCR
        run: |
          CHART=$(ls prometheus-exporter-*.tgz)
          helm push "$CHART" oci://ghcr.io/${{ steps.vars.outputs.chart_owner }}/charts
